keys:
     telegram_token: telegram api token goes here
     google_dev_key: google custom seaech API key (if needed)
     google_cse_id: see above
     channel: vk.com channel for autorepost
     vk_token: vk api token goes here

sys_paths:
    leet_dictionary: resources/leetdict.txt
    meme_font: resources/impact.ttf

path: #you can change these
    yandere_search: userdata/
    gifs: userdata/mp4/
    glitch: userdata/glitch/
    instagram: userdata/instagram/
    kek: userdata/kek/
    lego: userdata/lego/
    liquid: userdata/liquid/
    memes: userdata/memes/
    nya: userdata/nya/
    tts: userdata/
    vk: userdata/channel