keys:
     telegram_token: 123455
     bing_api_key: 123456

path:
    gifs: examples/gifs/
    memes: examples/memes/
    meme_font: resources/impact.ttf
    lego: examples/lego/
    nya: examples/nya/
    kek: examples/kek/
    instagram: examples/instagram/
    anime: examples/
    liquid: examples/
