keys:
     telegram_token: =====key=====

features:
    anime_search:
        enabled: true
        commands_gelbooru:
            - gelbooru
            - gel
        commands_yandere:
            - a
            - yandere
            - yan

    glitch:
        enabled: true
        commands: 
            - glitch
        path: userdata/glitch/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp

    google_search:
        enabled: true
        commands_image:
            - google
            - img
        commands_gif:
            - gif
            - gifs

    graphs:
        enabled: true
        commands:
         - activity
        db_path: userdata/
        path: userdata/
        graph_logo: resources/graph_logo.jpg

    jpeg:
        enabled: true
        commands:
            - jpeg
        path: userdata/jpeg/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .webp

    kek:
        enabled: true
        commands: 
            - kek
        path: userdata/kek/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp
            - .gif
            - .mp4

    leetspeak:
        enabled: true
        commands: 
            - leet
        leet_dictionary: resources/leetdict.txt

    lego:
        enabled: true
        commands: 
            - lego
        path: userdata/lego/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .gif
            - .webp

    liquid:
        enabled: true
        commands: 
            - liq
        path: userdata/liquid/

    logging:
        enabled: true
        path: userdata/

    meme:
        enabled: true
        commands: 
            - meme
            - memos
        path: userdata/meme/
        fonts:
            impact:
                name: impact
                path: resources/impact.ttf
            lobster:
                name: lobster
                path: resources/lobster.ttf
            comic:
                name: comic
                path: resources/comic.ttf
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp

    nya:
        enabled: true
        commands: 
            - nya
        path: userdata/nya/
        
    palette:
        enabled: true
        commands:
            - palette
            - colors
        path:
            userdata/palette/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp
            - .bmp
            - .gif

    rate:
        enabled: true
        commands:
            - rate

    roll:
        enabled: true
        commands:
            - roll
            
    system:
        enabled: true
        commands: 
            - system
    tts:
        enabled: true
        commands: 
            - say
        path: userdata/tts/
        
    zalgo:
        enabled: true
        commands:
            - zalgo
